version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./DockerFile
    env_file:
      - .env
    restart: always
    ports:
      - "9999:9999"
      - "5432:5432"
    networks:
      - dokploy-network

    # Add Traefik labels here when you have a domain
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inflection-app.rule=Host(`app.inflection.network`)"
      - "traefik.http.routers.inflection-app.entrypoints=websecure"
      - "traefik.http.routers.inflection-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.inflection-app.loadbalancer.server.port=9999"

networks:
  dokploy-network:
    external: true