version: "3"

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    restart: always
    ports:
      - "9999:9999"
      - "5432:5432"
    networks:
      - dokploy-network

    # Add Traefik labels here when you have a domain
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inflection-api.rule=Host(`app.inflection.network`)"
      - "traefik.http.routers.inflection-api.entrypoints=websecure"
      - "traefik.http.routers.inflection-api.tls.certResolver=letsencrypt"
      - "traefik.http.services.inflection-api.loadbalancer.server.port=9999"

networks:
  dokploy-network:
    external: true