version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    restart: always
    expose:
      - "9999"
    networks:
      - dokploy-network

    # Add Traefik labels here when you have a domain
   labels:
    - "traefik.enable=true"
    - "traefik.http.routers.inflection-app.rule=Host(`app.inflection.network`)"
    - "traefik.http.routers.inflection-app.service=inflection-app-svc"  # Explicit service name
    - "traefik.http.services.inflection-app-svc.loadbalancer.server.port=9999"  # Your app's internal port
    - "traefik.http.routers.inflection-app-secure.rule=Host(`app.inflection.network`)"
    - "traefik.http.routers.inflection-app-secure.service=inflection-app-svc"
    - "traefik.http.routers.inflection-app-secure.tls=true"
    - "traefik.http.routers.inflection-app-secure.tls.certresolver=letsencrypt"  # Assuming Dokploy's default 

networks:
  dokploy-network:
    external: true