
version: "3.8"
services:
  app:
    build:
      context: .  # Root directory containing turbo.json, package.json, etc.
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: unless-stopped
    ports:
      - "9999:9999"
      - "5432:5432"
    env_file:
      - .env
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mini-app.rule=Host(`yourdomain.com`) || Host(`www.yourdomain.com`)"
      - "traefik.http.routers.mini-app.entrypoints=websecure"
      - "traefik.http.routers.mini-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.mini-app.loadbalancer.server.port=9999"
      - "traefik.http.middlewares.mini-app-redirect.redirectregex.regex=^https://www\\.yourdomain\\.com/(.*)"
      - "traefik.http.middlewares.mini-app-redirect.redirectregex.replacement=https://yourdomain.com/$${1}"
      - "traefik.http.middlewares.mini-app-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.mini-app-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.mini-app-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.mini-app-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.mini-app-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.middlewares.mini-app-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.mini-app.middlewares=mini-app-redirect,mini-app-headers"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
networks:
  dokploy-network:
    external: false
    driver: bridge
