
version: "3.8"
services:
  app:
    build:
      context: .  # Root directory containing turbo.json, package.json, etc.
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    restart: unless-stopped
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.infinity-app.rule=Host(`app.inflection.network`)"
      - "traefik.http.routers.infinity-app.entrypoints=websecure"
      - "traefik.http.routers.infinity-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.infinity-app.loadbalancer.server.port=9999" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
networks:
  dokploy-network:
    external: false
    driver: bridge
