# Root nixpacks.toml for monorepo
# This file is used when deploying the entire monorepo
# For individual services, use the specific nixpacks.toml files in each app directory

[providers]
node = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"
